travis:
  secure:
    BINSTAR_TOKEN: WEwim6AIVdj2eYZM+g+xGTGNJxo9AYUf3/tY35QqebN2nxCoBtOXmcPowAVr5HJONyIPVjv/JvftEQf4QENInbta9xbNWDCqyqwLCwFI5nYGtoGmytYyB9VlxRVrfrRyiVPXTbIwGcnTkhp4XWKmquFl8Vt3pLwhxdWnCePToXvoB5yGEVdz3nKHDAXLi6h0zrZCtkiEjyNFFzmTSZU6Qqlox2CpXx/BUTWtX0Sxx/tiiczCPZ6C1Z08pYH5y4dQ0yZpnUDvohASempj4nZBXvGF0IaYPc+dURs27JlqEyn5FCOaAN86U/aFsNGXV7zS5Gl6deCGBcwV8D3kaf/urpxretWIt0GuaRmjivcmKJI0T7ku52CoaHHsIMwT3DNwAHJADrMoiaS/q4npBDIvvajbj9CPZq3mZHhZA5OHw1pgPpyc0Dh9pqK2NO7M+z5YH3MX9+GqJAtU/uq5dRPUqVSmvdDBFOdmmuTOVwK+NLlY8gGKRQtSMV8/+l3lK0zczkCPPXRffynYw2OYDbSwFxs0EJHvuF+dQ+LBBQGYEUS+qgbZKgF0s2Hbb0Ud2RDpC5BPDtXvPYrnTdmzXOc10JA16HE0PZYLaDmCoAu4evULhaGKUcC9j8YFk/xyZSs6zwi4uJX4fbaLWoxsi7ehmLEY0tKlM68ahpdHkhXQkKM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
