travis:
  secure:
    BINSTAR_TOKEN: g3kH4VqEsxeXfsSox74xPuI8yY0rN+WbOGWqeDAt/XxiPCZ/sdye+BM7GheVGaes1YFQ/tcgffFVKV9rTcW3yAeijyis/jfAK3wGJdU2kTZLIGtUTU4L/t2BgMycPtJMzH70eoRH7bbZ9JHY6P0Am46SA+21Qw90VK8ZoHphOHSqzZ/hWZHoh8oSEr7RukMkTAGEfCPP7CM7Ts1sEWL9ItNUaldqhcpFLQRvNGcg7H2P0CDin1IJZ0jW2AdDJsUV8zW0XMcBQ5RTj42yn7SB1I9yodhY75KCEisP0slqbkIn0XzwHVm5UHb63lsACFNzD3De+X9+DRVku30a2Z4ykdIkpw+hrbAyP6YlNdCT/vmLzx1h42lZ+ug+CG8dUIxsMLZa3TIVMmKMGyMdEuizY7drb37SadfiZHBJRlsgu3IPYtpnV7xf3IWvfNUEJL/JfbqPrLoxFtT9wtzlmA5I+gSFNZj5FZg4JeVxcYw4T8h1TZNou9Apwla9mZoJwuFDkrvfzMlJIlt93Wx0BRnyOWRYMLbuCN1uxs8fQMG1y4w1X0vLU1t34VTJrNRz6yGdO2XWKtj3QMk/GBXFzXQhncgN5j7zlBOl4UxQxv/mrg50kmqplLaZgqeCe+Sym1jqQAYZsTrRycj8ALvnnR0vAFJfVksZ+W4AltdC1EJYNm4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
