travis:
  secure:
    BINSTAR_TOKEN: qOsNMquB3KSu1B3oxqTYsIDQIFd4XxwTfLY3X9XfhbgdM7UiL4H5L4O180caPg8Ey5MQSCbWZZU4rJzTX/hrTesDbt5+OV+NZJE7agkV0Z8BU//REAsQm8yPm1s7/HSuPAlMZ2D77494peil287wnHXfqyGw1ikKC7cpxcPNDc+o1v/Ic0W9CxArVHvXimyaaG7CWNvD0nTlAcrrOf8xnPMj10Gagl0ayJWr/6CT+nwNrcW7Jk3KzFbu8uPm4QR3xtuWzp8bhCCZWTMvJly3r+uDPVGjGTY8lgTuz5xR4YHDAIQCdAwjUEMGR8l5QgUpqN7M/RnaumxnxYS+pGuNmloMCZsF4NeJ4me3eJPyhcvC8LkmK89T6YdKQVl2KM8VTBwlLD2ausNEhzAXBsdVtn+vPg/tCy72SFQkyBVqJId6It7rgYajI42In+dXEOtwAj0ysaBKehHGdmBpRxqNLLbHvJNQL2yfdQSM71XfDpmeMzfJGFdN0VjkyTMzOuCmZXTukO31MEJ77GfVNRv75SY3OoPWRrruXUWdlec1PwxcCgFGf6ga3NBmrbxkfVNkDLqta2fsPqQbQRfkep2JD7ZcpSxexjWFBNjRyJAWOemvggLrQZO7O6Rm0/hG6+WNbTjbbQLzREEPVT10UXn65mAMce/WENe8AstqHqwjDz0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
